#
# http://wiki.ros.org/hector_mapping
#
  
base_frame:                 footprint
map_frame:                  map
odom_frame:                 footprint

map_resolution:             0.1
map_size:                   10000
map_start_x:                0.9
map_start_y:                0.5
map_update_distance_thresh: 0.4
map_update_angle_thresh:    0.9
map_pub_period:             2.0
map_multi_res_levels:       3

update_factor_free:         0.4
update_factor_occupied:     0.9

laser_min_dist:             0.4
laser_max_dist:             30.0
laser_z_min_value:          0
laser_z_max_value:          10

pub_map_odom_transform:     true
output_timing:              false
scan_subscriber_queue_size: 5

pub_map_scanmatch_transform: false
tf_map_scanmatch_transform_frame_name: hector_mapping/scanmatcher_frame



#
# Notes
#

# To use Odometry only from hector_maping set:
# odom_frame:               Pioneer3AT/base_link
# and in rosaria.yaml set:
# tf_prefix:                Pioneer3AT_tmp
  


